#!/bin/sh

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config border_width         2
bspc config window_gap		10
bspc config top_padding		40

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-1   -d 6 7 8 9 0

bspc config padding_top		32
