#!/bin/sh

wmname i3
xsetroot -cursor_name left_ptr

bspc monitor HDMI-0 -d 1 3 5 7 9
bspc monitor DP-1   -d 2 4 6 8 0

sxhkd &

bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap		10
bspc config top_padding		40

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
