msg_color               #ffffff
msg_font                edgesi:size=14
msg_x                   50%
msg_y                   50%

background_style        tile
background_color        #000000

# Input controls (relative to panel)
input_panel_x           10%
input_panel_y           50%
input_name_x            237
input_name_y            106
input_pass_x            237
input_pass_y            106
input_font          	edges:size=14
input_color             #006BCB

